### PR TITLE
Recognize the legitimacy of `language: minimal`

### PR DESCRIPTION
**Pull request by meatballhat**
Addresses travis-ci/travis.rb#504

### CODE REVIEW

**Comment by carlad** [comment]
According to @rkh API needs to be updated. I updated on a branch and deployed to org-staging.
https://github.com/travis-ci/travis-api/pull/534

I've created a build with `language: minimal` in the .travis.yml, and things seem to work fine:
https://staging.travis-ci.org/carlad/pusher-live-test/jobs/611920/config

However I'm not sure if that's what needs to be tested. Let me know when this is merged and I can help out  updating api and pro-api...

**Comment by Akhond-Zada** [comment]
Hello . Guys

**Comment by carlad** [comment]
Hi @Akhond-Zada sorry this has taken so long - I still need to update `travis-api` to use this change. Am doing that now so hold tight...

**Comment by carlad** [comment]
Okay, api is updated and deployed. Hopefully this will be working as required now. Thanks again for your patience.

**Pull request merged**
