### PR TITLE
add support for D language

### PR DESCRIPTION
**Pull request by MartinNowak**
- add language entry

- add `d:` to specify compiler versions

### CODE REVIEW

**Comment by MartinNowak** [comment]
Should we still update the lint command?

**Comment by rkh** [comment]
What's the list of `d` compilers?

**Comment by MartinNowak** [comment]
It's documented here, new compilers are supported when released.
http://docs.travis-ci.com/user/languages/d/#Choosing-compilers-to-test-against
Basically anything that matches these regexes should work.
https://github.com/travis-ci/travis-build/blob/936fa52aa709901537134b45a7cb88002709beca/lib/travis/build/script/d.rb#L89

**Comment by rkh** [comment]
I think it would be possible to have different accepted values for compiler, but maybe we should just accept anything for now?

**Comment by MartinNowak** [comment]
> but maybe we should just accept anything for now?

Anything would be fine I for now.

**Comment by MartinNowak** [comment]
Ping, I also regenerated the SPEC.md.

**Pull request merged**
